### ISSUE TITLE
doc conventional commits

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-DMI-Bot#119]
Add to the readme the standard about convetional commits
```
feat()
chore()
fix()
test()
refact()
doc()
```

**Comment by Guberlo** [comment]
I think it would actually be better if we create a CONTRIBUTING.md file and add those in there, maybe also followed by a small guide on the code of conduct and the best way to make a PR.

**Comment by Helias** [comment]
I totally agree, let's do it :wink: 

Imho, we should say how-to-make-a-PR besides how to write the commits details and yes a lot of stuff.

Like... "if you contribute at least on one projects of this you will be added to the telegram group UNICT Devs..etc."
