### ISSUE TITLE
Deprecated library: dryscrape

### ISSUE THREAD

**Issue by Guberlo** [UNICT-DMI/Telegram-DMI-Bot#131]
As the official [repository](https://github.com/niklasb/dryscrape) mentions:
__NOTE:This package is not actively maintained. It uses QtWebkit, which is end-of-life and probably doesn't get security fixes backported. Consider using a similar package like [Spynner](https://github.com/makinacorpus/spynner) instead.__

Also, I'm not sure if this is compatible with ubuntu 20.04.

**Comment by Helias** [comment]
it's strange that this Spynner is not written in python3

**Comment by franciscopablorusso** [comment]
See the **README.md** file, we solved the two mayor compatibility problems on **Ubuntu 20.04**
