### ISSUE TITLE
Suggested commands

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-DMI-Bot#136]
I remember that in some updates Telegram added the possibility to add the "suggested commands" from the source code and not only from BotFather.

Here what I mean
https://stackoverflow.com/questions/34457568/how-to-show-options-in-telegram-bot

We need to investigate and understand if it is possible to move this suggestions to the source code

**Comment by TendTo** [comment]
It can easily be done with the _set_my_commands_ method [(documentation)](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html)

Example (used in the main.py file):
``` python
def add_commands(up: Updater):
    """Adds the list of commands with their description to the bot

    Args:
        up (Updater): supplyed Updater
    """
    commands = [
        BotCommand("start", "presentazione iniziale del bot"),
        BotCommand("spot", "inizia a spottare"),
        BotCommand("help ", "funzionamento e scopo del bot"),
        BotCommand("rules ", "regole da tenere a mente"),
        BotCommand("settings", "cambia le impostazioni di privacy"),
...
    ]
    up.bot.set_my_commands(commands=commands)
```

**Comment by Helias** [comment]
@TendTo very good 👍

**Comment by franciscopablorusso** [comment]
I remember that you can do the same (in a very simple way, without any type of code) from @BotFather's bot options:
write command "/mybots" >> [SELECT THE BOT YOU WANT TO MODIFY] >> press "Edit Bot" button >> press "Edit Commands"
- [x] Et voilà!

Obviously only the bot's owner can modify them in this way and **you have totally zero interaction with code**.
