### ISSUE TITLE
Migrazione ad aiogram

### ISSUE THREAD

**Issue by Herbrant** [UNICT-DMI/Telegram-DMI-Bot#160]
Potrebbe essere interessante migrare a https://github.com/aiogram/aiogram sfruttando la programmazione asincrona.
Il progetto sembra abbastanza supportato e promette bene.
Una proposta per il futuro.

**Comment by aegroto** [comment]
Ho provato in un progetto personale aiogram e la trovo ancora un po' instabile. Stavo usando un boilerplate che aveva già un po' di parallelismo in se quindi potrebbe essere stato quello il problema, ma farei qualche altro tentativo prima di migrare l'intero bot a quel framework.
