### ISSUE TITLE
Rework menù di navigazione di Drive

### ISSUE THREAD

**Issue by aegroto** [UNICT-DMI/Telegram-DMI-Bot#178]
![screen](https://user-images.githubusercontent.com/11978802/129551945-5f1c7916-7d8f-4f7c-9d78-e32bf799b6b3.png)

Sarebbe meglio avere un solo messaggio con la lista delle cartelle e dei file, che si aggiorna ad ogni click, mentre attualmente viene inviato un nuovo messaggio con la cartella aperta.

Il codice da modificare è il callback _drive_handler_ a linea 39 di module/commands/gdrive.py. In particolare, la chiamata a _bot.sendMessage_ a linea 71 deve essere modificata in un _editMessageText_ (https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html#telegram.Bot.edit_message_text). Al contrario di quello che può sembrare, _editMessageText_ permette di modificare sia il testo sia il menù del messaggio.

Non assicuro che basti modificare quella linea, ma il grosso del lavoro riguardante le meccaniche del funzionamento dovrebbe essere fatto una volta toccato quel punto.

**Comment by Helias** [comment]
In parte l'ho trovato comodo avere lo storico delle cartelle che ho visitato, pero' effettivamente e' un po' spammoso.

**Comment by drendog** [comment]
@Helias Magari si potrebbero implementare delle breadcrumbs per tutte le sottocartelle, anche se non sono sicuro che su telegram sia fattibile
