### ISSUE TITLE
Aggiornare Pagina Ricevimento su DMIBOT (comando /ricevimenti)

### ISSUE THREAD

**Issue by filippocampo98** [UNICT-DMI/Telegram-DMI-Bot#188]
Ogni anno sul sito del DMI viene inserita una sezione ricevimenti dove ci sono tutti i docenti con i rispettivi orari di ricevimento.

La pagina si trova a questo link: http://web.dmi.unict.it/corsi/l-31/ricevimento.

L'idea era quella di estrapolare i dati e renderli visibili quando si scriveva il comando /ricevimenti il ricevimenti dei vari prof. che poi possiamo decidere se farlo il comando con il singolo professore o renderlo generico la visualizzazione del contenuto.

**Comment by Helias** [comment]
Da non dimenticare anche gli altri corsi di laurea interni al DMI
http://web.dmi.unict.it/corsi/l-35/ricevimento
http://web.dmi.unict.it/corsi/LM-40/ricevimento
http://web.dmi.unict.it/corsi/LM-18/ricevimento
