### ISSUE TITLE
Multi lang issue

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-DMI-Bot#208]
related to https://github.com/UNICT-DMI/Telegram-DMI-Bot/pull/207

Bug:
when I dive into the dmi bot menu buttons the text languages switch randomly

How to reproduce the bug:
 - /help
 - click on "Notes and cloud"
 - you'll get the text in italian

**Comment by LightDestory** [comment]
The language switch is not our resposability. The code will provide the language based on the `language_code` provided by Telegram.

Can you provide the following info:
- Application in use
- System language

**Comment by LightDestory** [comment]
Confirmed, I am looking into it
