### ISSUE TITLE
Cancellazione del comando /trasporto_urbano_unict

### ISSUE THREAD

**Issue by filippocampo98** [UNICT-DMI/Telegram-DMI-Bot#217]
Visto che la linea BRTU è stata sospesa e non esiste più sarebbe meglio eliminarla dal DMI BOT al fine di non avere comandi che poi ufficialmente non servono visto la situazione odierna.

**Comment by Valeri0p** [comment]
Al momento si potrebbe sostituire con https://www.amts.ct.it/mappa-delle-linee?percorso=901
Si spera che l'anno prossimo riprenda il servizio navetta da Milo...

**Comment by filippocampo98** [comment]
questo si....non ci avevo pensato!

**Comment by filippocampo98** [comment]
ho fatto un pull request per il cambiamento delle informazioni all'interno del comando /trasporto_urbano_unict
