### ISSUE TITLE
get "aule studio" times and location

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-DMI-Bot#240]
make a command that shows all the places to study, geo-location and times

**Comment by filippocampo98** [comment]
al clic del comando deve avere orari di apertura e chiusura delle aule studio, aule studio disponibili in dipartimento con geolocazione (come spiegazione di dove si trova o stile Maps)? @Helias

**Comment by Picred** [comment]
Secondo me potrebbe andare anche un link di Google Maps o proprio un messaggio "location" integrato di telegram.

Penso che per le spiegazioni proprio scritte possono essere trovare su Maps stesso o comunque vedendo il percorso
