### ISSUE TITLE
Hard coded value for year in scrapers exams and lessons

### ISSUE THREAD

**Issue by Wornairz** [UNICT-DMI/Telegram-DMI-Bot#68]
The actual scrapers for exams and lessons use a hardcoded value for the year (example "120" mean 2019/2020).
It would be good if this value could be generated every year.

**Comment by Helias** [comment]
The algorithm could be:
```python
current_year = "2017/2018"
id = "1" + current_year[-2:] # id = 118
```

it works for `2019/2020` and `2017/2018`

**Comment by Warcreed** [comment]
Ok, I'm going to work on that
