### ISSUE TITLE
Comando per mostrare tutti i gruppi Telegram del CdL Informatica Triennale

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-DMI-Bot#92]
Al comando /gruppi inviare il seguente link 
https://unict-dmi.github.io/unict-telegram-channels-groups/#/channels

(Thanks @Gigi-G)

**Comment by Helias** [comment]
@InfernoMentale
@guberlo

**Comment by Helias** [comment]
Questa issue è assegnata a @franciscopablorusso, non svolgetela.

**Comment by franciscopablorusso** [comment]
> "Al comando /gruppi inviare il seguente link
> https://unict-dmi.github.io/unict-telegram-channels-groups/#/channels
> 
> (Thanks @Gigi-G)"

Alla fine il link corretto per gruppi era: 
https://unict-dmi.github.io/unict-telegram-channels-groups/#/groups

Sto pushando! ;-)
