### ISSUE TITLE
Aggiungere altri pulsanti oltre ad "HELP ?" nella tastiera del bot

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/Telegram-DMI-Bot#94]
Aggiungere i pulsanti:
- 📬 Segnalazione Rappresentanti 
- 🗓 Aulario 
- ☁️ Cloud 

Similmente al bot @ERSU_Bot

**Comment by Helias** [comment]
@InfernoMentale
@guberlo

**Comment by Guberlo** [comment]
Avevo già dato un'occhiata 👍

Sto cercando di aggiustare la chiamata ad informative_callback per poter gestire anche i messaggi (tipo: 📬 Segnalazione Rappresentanti) e matchare il file .md. 

Se riesco a trovare un po' di tempo conto di fare una PR entro stasera
